-- RL Roulette Database Schema
-- This file contains only the table structure (no data)
-- Generated by scripts/dump_db.py

BEGIN TRANSACTION;
CREATE TABLE predictions (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                session_id INTEGER NOT NULL,
                spin_id INTEGER,
                predicted_number INTEGER,
                actual_number INTEGER,
                predicted_color TEXT,
                actual_color TEXT,
                color_correct INTEGER,
                predicted_parity TEXT,
                actual_parity TEXT,
                parity_correct INTEGER,
                predicted_high_low TEXT,
                actual_high_low TEXT,
                high_low_correct INTEGER,
                predicted_dozen INTEGER,
                actual_dozen INTEGER,
                dozen_correct INTEGER,
                predicted_column INTEGER,
                actual_column INTEGER,
                column_correct INTEGER,
                timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP, predictor_type TEXT,
                FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE CASCADE,
                FOREIGN KEY (spin_id) REFERENCES spins(id) ON DELETE SET NULL
            );
CREATE TABLE predictor_stats (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                session_id INTEGER NOT NULL,
                predictor_type TEXT NOT NULL,
                total_predictions INTEGER DEFAULT 0,
                number_correct INTEGER DEFAULT 0,
                color_correct INTEGER DEFAULT 0,
                parity_correct INTEGER DEFAULT 0,
                high_low_correct INTEGER DEFAULT 0,
                dozen_correct INTEGER DEFAULT 0,
                column_correct INTEGER DEFAULT 0,
                updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE CASCADE,
                UNIQUE(session_id, predictor_type)
            );
CREATE TABLE sessions (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                name TEXT NOT NULL,
                source TEXT DEFAULT 'manual',
                casino TEXT DEFAULT '',
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                notes TEXT DEFAULT ''
            );
CREATE TABLE spins (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                session_id INTEGER NOT NULL,
                number INTEGER NOT NULL CHECK(number >= 0 AND number <= 36),
                timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE CASCADE
            );
CREATE TABLE statistics_cache (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                stat_type TEXT NOT NULL,
                session_id INTEGER,
                data BLOB,
                computed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE CASCADE
            );
CREATE INDEX idx_spins_session 
            ON spins(session_id)
        ;
CREATE INDEX idx_spins_timestamp 
            ON spins(timestamp)
        ;
CREATE INDEX idx_predictions_session 
            ON predictions(session_id)
        ;
CREATE VIEW spin_components AS
            SELECT 
                s.id,
                s.session_id,
                s.number,
                s.timestamp,
                CASE 
                    WHEN s.number = 0 THEN 'green'
                    WHEN s.number IN (1,3,5,7,9,12,14,16,18,19,21,23,25,27,30,32,34,36) THEN 'red'
                    ELSE 'black'
                END as color,
                CASE 
                    WHEN s.number = 0 THEN 'zero'
                    WHEN s.number % 2 = 1 THEN 'odd'
                    ELSE 'even'
                END as parity,
                CASE 
                    WHEN s.number = 0 THEN 'zero'
                    WHEN s.number >= 19 THEN 'high'
                    ELSE 'low'
                END as high_low,
                CASE 
                    WHEN s.number = 0 THEN 0
                    WHEN s.number <= 12 THEN 1
                    WHEN s.number <= 24 THEN 2
                    ELSE 3
                END as dozen,
                CASE 
                    WHEN s.number = 0 THEN 0
                    ELSE ((s.number - 1) % 3) + 1
                END as col,
                CASE 
                    WHEN s.number = 0 THEN 0
                    ELSE ((s.number - 1) / 3) + 1
                END as row
            FROM spins s;
CREATE INDEX idx_predictor_stats_session
            ON predictor_stats(session_id)
        ;
DELETE FROM "sqlite_sequence";
