#!/usr/bin/env python
"""
Create a SCHEMA-ONLY SQL dump of the SQLite database (no data).
This exports only the table structure (CREATE TABLE statements) without INSERT statements.

Usage:
  python scripts/dump_db.py
Or specify an output file:
  python scripts/dump_db.py out.sql
"""
from pathlib import Path
import sys
import sqlite3

from pathlib import Path as _Path
DEFAULT_DB_PATH = _Path(__file__).parent.parent / "data" / "roulette.db"


def main(out_file: str = None):
    db_path = DEFAULT_DB_PATH
    if not db_path.exists():
        print(f"Database not found at: {db_path}")
        return

    out_file = Path(out_file) if out_file else Path(__file__).parent.parent / "data" / "roulette_dump.sql"
    out_file.parent.mkdir(parents=True, exist_ok=True)

    print(f"Dumping SCHEMA from: {db_path}")
    print(f"Writing SQL to: {out_file}")

    conn = sqlite3.connect(str(db_path))
    
    with open(out_file, "w", encoding="utf-8") as f:
        # Write header comment
        f.write("-- RL Roulette Database Schema\n")
        f.write("-- This file contains only the table structure (no data)\n")
        f.write("-- Generated by scripts/dump_db.py\n\n")
        
        # Export only schema (filter out INSERT statements)
        for line in conn.iterdump():
            # Skip INSERT statements and transaction control for data
            if line.startswith('INSERT INTO') or line.startswith('COMMIT'):
                continue
            # Keep CREATE TABLE, CREATE INDEX, BEGIN TRANSACTION, etc.
            f.write(f"{line}\n")

    conn.close()
    print("Schema dump complete (data excluded)")


if __name__ == '__main__':
    out_arg = sys.argv[1] if len(sys.argv) > 1 else None
    main(out_arg)

